return function()
    https = require 'https'
    utf8 = require 'utf8'
    g3d = require 'libraries.g3d'
    --lollipop = require 'libraries.lollipop'
    neuron = require 'libraries.neuron'
    loveframes = require 'libraries.loveframes'
    moonshine = require 'libraries.moonshine'
    slab = require 'libraries.slab'
    class = require 'libraries.classic'
    camera = require 'libraries.camera'
    shack = require 'libraries.shack'
    collision = require 'libraries.collision'
    deep = require 'libraries.deep'
    discordrpc = require 'libraries.discordRPC'
    gamestate = require 'libraries.gamestate'
    gamejolt = require 'libraries.gamejolt'
    flux = require 'libraries.flux'
    json = require 'libraries.json'
    multouch = require 'libraries.multouch'
    lume = require 'libraries.lume'
    nativefs = require 'libraries.nativefs'
    timer = require 'libraries.timer'
end